### ISSUE TITLE
Support Geyser Standalone

### ISSUE THREAD

**Issue by obtar** [Heath123/debuginfo-be#10]
I tried to run on the Geyser-Standalone, so i can debug. But it doesn't work.

This is logs
`[23:11:36.847 main/INFO] 正在加载扩展...
[23:11:36.894 main/ERROR] 无法加载位于文件夹 ~/extensions/debuginfo-be.jar at debuginfo-be.jar：
org.geysermc.geyser.api.extension.exception.InvalidDescriptionException: Failed to load extension description for ~/extensions/debuginfo-be.jar
	at org.geysermc.geyser.extension.GeyserExtensionLoader.extensionDescription(GeyserExtensionLoader.java:128) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.lambda$loadAllExtensions$0(GeyserExtensionLoader.java:180) ~[Geyser-Standalone.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.loadAllExtensions(GeyserExtensionLoader.java:168) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.api.extension.ExtensionManager.loadAllExtensions(ExtensionManager.java:88) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionManager.init(GeyserExtensionManager.java:48) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.GeyserImpl.<init>(GeyserImpl.java:215) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.GeyserImpl.load(GeyserImpl.java:863) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserEnable(GeyserStandaloneBootstrap.java:225) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserInitialize(GeyserStandaloneBootstrap.java:194) [Geyser-Standalone.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:172) [Geyser-Standalone.jar:?]
Caused by: java.nio.file.NoSuchFileException: /extension.yml
	at jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:861) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:751) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:270) ~[jdk.zipfs:?]
	at java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2897) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2930) ~[?:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.extensionDescription(GeyserExtensionLoader.java:124) ~[Geyser-Standalone.jar:?]
	... 10 more`

**Comment by MrBsng** [comment]
@obtar it is not an extension and it cannot run on geyser standalone it has to run with geyser-spigot.

**Comment by obtar** [comment]
Ok, i know it.
